openapi: 3.0.0
info:
  title: contact_manager
  version: 1.0.0
servers:
  - url: http://localhost:3050

# Apply JWT auth globally (except for /login)
security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Contacts
  - name: Auth

paths:
  /api/contacts:
    post:
      tags:
        - Contacts
      summary: Create Contact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: contact 1
                phone: '0123123123'
                address: Cairo
                notes: >
                  this is an address in a country called Egypt in the Africa Continent
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

    get:
      tags:
        - Contacts
      summary: List Contacts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            example: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            example: 10
          description: Number of contacts per page
        - in: query
          name: name
          schema:
            type: string
            example: Merna
          description: Filter by contact name
        - in: query
          name: address
          schema:
            type: string
            example: Cairo
          description: Filter by contact address
        - in: query
          name: phone
          schema:
            type: string
            example: "0123456789"
          description: Filter by contact phone
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /api/contacts/6840ebd4e485c774373399ad:
    delete:
      tags:
        - Contacts
      summary: Delete Contact
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

    put:
      tags:
        - Contacts
      summary: Update Contact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: 'this is an updated contact'
                phone: '0123123123'
                address: Cairo
                notes: >
                  this is an address in a country called Egypt in the Africa Continent
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

  /api/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: user1
                password: user1
      # No auth required here
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
